/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': 'rgb(var(--tc-secondary-fill) / <alpha-value>)',
        surface: '#0f141b',
        'on-secondary-container': 'rgb(var(--tc-on-secondary-fill) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--tc-on-accent-fill) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--tc-on-secondary-fill) / <alpha-value>)',
        'primary-container': 'rgb(var(--tc-primary) / <alpha-value>)',
        primary: 'rgb(var(--tc-accent) / <alpha-value>)',
        background: '#0f141b',
        'surface-container': '#18212c',
        outline: '#74879b',
        'surface-container-low': '#111a24',
        'secondary-fixed-dim': 'rgb(var(--tc-accent-hover) / <alpha-value>)',
        'surface-container-lowest': '#090d12',
        'surface-container-highest': '#263342',
        tertiary: '#a6b7e0',
        'on-error': '#ff8f96',
        'secondary-fixed': 'rgb(var(--tc-secondary-hover) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--tc-on-primary) / <alpha-value>)',
        'on-surface': '#e4ebf2',
        'on-primary': '#ffffff',
        'outline-variant': '#2b3947',
        'on-surface-variant': '#a9b7cb',
        'on-background': '#e4ebf2',
        'on-primary-fixed': '#ffffff',
        'surface-container-high': '#1f2b38',
        secondary: 'rgb(var(--tc-accent-fill) / <alpha-value>)',
        'on-secondary': '#0a2530',
        'surface-variant': '#1f2b38',
      },
      fontFamily: {
        sans: ['Geist Variable', 'Geist', 'system-ui', '-apple-system', 'sans-serif'],
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        gutter: '24px',
        'section-gap': '128px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
