export const texts = {
  authorizedCenter: 'Centro de Servicio Técnico Autorizado',
  serviceOrder: 'ORDEN DE SERVICIO',
  date: 'Fecha',
  customerInfo: 'Información del Cliente',
  deviceInfo: 'Información del Dispositivo',
  problemDescription: 'Descripción del Problema',
  customerAuthorization: 'Autorización del Cliente',
  digitalSignature: 'Firma Digital/Manual',
  estimatedTotal: 'Total Estimado',
  exclTaxes: 'Excl. impuestos aplicables',
  cutHere: 'Cortar aquí para copia técnica',
  technicalRoutingCopy: 'Copia de Ruta Técnica',
  priority: 'Prioridad',
  standard: 'ESTÁNDAR',
  diagnosticChecklist: 'Lista de Verificación de Diagnóstico',
  powerSupply: 'Fuente de Alimentación',
  batteryHealth: 'Salud de la Batería',
  motherboard: 'Placa Madre',
  coolingSystem: 'Sistema de Refrigeración',
  timeTracking: 'Registro de Tiempo',
  start: 'Inicio',
  end: 'Fin',
  partNumberDescription: 'Número de Parte / Descripción',
  qty: 'Cant.',
  location: 'Ubicación',
  technicianProgressNotes: 'Notas de Progreso del Técnico',
  technicianSignature: 'Firma del Técnico',
  techId: 'ID Técnico',
  finalQCStatus: 'ESTADO FINAL DE CONTROL DE CALIDAD',
  formId: 'Formulario SO-TECH-2024-V2',
  confidential: 'Documento Interno Confidencial',
  page: 'Página 1 de 1',
  warranty: 'GARANTÍA',
  warrantyTerms: 'Términos y Condiciones de Garantía',
};
