import type { ServiceOrderData } from '../../types/pdfConfig/pdfConfig.types';

export const defaultData: ServiceOrderData = {
  companyName: 'TechFix Reparaciones',
  companyAddress: 'Av. Corrientes 1234, CABA, Argentina',
  companyPhone: '+54 11 4321-1234',
  companyEmail: 'info@techfix.com',
  orderNumber: `OS-${String(Math.floor(Math.random() * 9000) + 1000)}`,
  orderDate: new Date().toLocaleDateString('es-AR', { year: 'numeric', month: '2-digit', day: '2-digit' }),
  clientName: 'Juan Pérez',
  clientPhone: '+54 9 11 1234-5678',
  clientEmail: 'juan.perez@email.com',
  clientAddress: 'Av. Rivadavia 5678, CABA',
  clientId: 'DNI 30.123.456',
  deviceModel: 'iPhone 15 Pro Max',
  deviceImei: '356912087654321',
  deviceSerial: 'G6T5X7Y8Z9',
  deviceColor: 'Titanium Black',
  deviceStorage: '256 GB',
  deviceDescription: 'Pantalla OLED, cámara trasera triple',
  repairDescription: 'Reemplazo de pantalla OLED y reparación de botón de volumen',
  repairDiagnostic: 'Pantalla con líneas verticales y falta de respuesta táctil. Botón de volumen inferior dañado.',
  laborCost: '170.00',
  partsCost: '280.00',
  totalPrice: '450.00',
  warrantyMonths: '12',
  warrantyTerms: 'Garantía por defectos de fabricación y mano de obra por 12 meses. No cubre daños por agua, golpes o uso indebido posterior a la reparación.',
  securityType: 'pin',
  securityPin: '1234',
  securityPattern: 'Patrón en L (3x3)',
  securityNotes: 'El cliente ha proporcionado la clave de acceso.',
  technicianName: 'Carlos López',
  technicianNotes: 'Verificar la batería durante el proceso.',
  estimatedTime: '3 horas',
  showHeader: true,
  showFooter: true,
  headerText: 'ORDEN DE SERVICIO',
  footerText: 'Este documento es un comprobante de recepción de equipo.',
  fontSize: 10,
  margin: 18,
  showClientSection: true,
  showTechnicianSection: true,
  showSecurityInfo: true,
  showWarrantyTerms: true,
  showSignatures: true,
  showWatermark: false,
  watermarkUrl: '',
};
