// Lista de permisos disponibles en el sistema
export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard.view',
  
  // Reparaciones
  REPAIRS_VIEW: 'repairs.view',
  REPAIRS_CREATE: 'repairs.create',
  REPAIRS_EDIT: 'repairs.edit',
  REPAIRS_DELETE: 'repairs.delete',
  REPAIRS_ASSIGN: 'repairs.assign',
  
  // Clientes
  CLIENTS_VIEW: 'clients.view',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_EDIT: 'clients.edit',
  CLIENTS_DELETE: 'clients.delete',
  
  // Stock/Inventario
  STOCK_VIEW: 'stock.view',
  STOCK_CREATE: 'stock.create',
  STOCK_EDIT: 'stock.edit',
  STOCK_DELETE: 'stock.delete',
  STOCK_MOVEMENTS: 'stock.movements',
  
  // Ventas
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_EDIT: 'sales.edit',
  SALES_DELETE: 'sales.delete',
  
  // Caja
  CASH_VIEW: 'cash.view',
  CASH_OPEN: 'cash.open',
  CASH_CLOSE: 'cash.close',
  
  // Usuarios
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE_PERMISSIONS: 'users.manage_permissions',
  
  // Roles
  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_EDIT: 'roles.edit',
  ROLES_DELETE: 'roles.delete',
  
  // Empresas
  COMPANIES_VIEW: 'companies.view',
  COMPANIES_CREATE: 'companies.create',
  COMPANIES_EDIT: 'companies.edit',
  COMPANIES_DELETE: 'companies.delete',
  
  // Reportes
  REPORTS_VIEW: 'reports.view',
  REPORTS_SALES: 'reports.sales',
  REPORTS_REPAIRS: 'reports.repairs',
  REPORTS_STOCK: 'reports.stock',
  
  // Configuración
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',
  
  // Auditoría
  AUDIT_VIEW: 'audit.view',
  
  // Desarrollador
  DEVELOPER_VIEW: 'developer.view',
  DEVELOPER_MANAGE: 'developer.manage',
} as const;

// Permisos por defecto para cada rol
export const DEFAULT_ROLE_PERMISSIONS = {
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPAIRS_VIEW,
    PERMISSIONS.REPAIRS_CREATE,
    PERMISSIONS.REPAIRS_EDIT,
    PERMISSIONS.REPAIRS_DELETE,
    PERMISSIONS.REPAIRS_ASSIGN,
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_EDIT,
    PERMISSIONS.CLIENTS_DELETE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_CREATE,
    PERMISSIONS.STOCK_EDIT,
    PERMISSIONS.STOCK_DELETE,
    PERMISSIONS.STOCK_MOVEMENTS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_EDIT,
    PERMISSIONS.SALES_DELETE,
    PERMISSIONS.CASH_VIEW,
    PERMISSIONS.CASH_OPEN,
    PERMISSIONS.CASH_CLOSE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_CREATE,
    PERMISSIONS.ROLES_EDIT,
    PERMISSIONS.ROLES_DELETE,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.COMPANIES_CREATE,
    PERMISSIONS.COMPANIES_EDIT,
    PERMISSIONS.COMPANIES_DELETE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_SALES,
    PERMISSIONS.REPORTS_REPAIRS,
    PERMISSIONS.REPORTS_STOCK,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  DESARROLLADOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPAIRS_VIEW,
    PERMISSIONS.REPAIRS_CREATE,
    PERMISSIONS.REPAIRS_EDIT,
    PERMISSIONS.REPAIRS_DELETE,
    PERMISSIONS.REPAIRS_ASSIGN,
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_EDIT,
    PERMISSIONS.CLIENTS_DELETE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_CREATE,
    PERMISSIONS.STOCK_EDIT,
    PERMISSIONS.STOCK_DELETE,
    PERMISSIONS.STOCK_MOVEMENTS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_EDIT,
    PERMISSIONS.SALES_DELETE,
    PERMISSIONS.CASH_VIEW,
    PERMISSIONS.CASH_OPEN,
    PERMISSIONS.CASH_CLOSE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_CREATE,
    PERMISSIONS.ROLES_EDIT,
    PERMISSIONS.ROLES_DELETE,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.COMPANIES_CREATE,
    PERMISSIONS.COMPANIES_EDIT,
    PERMISSIONS.COMPANIES_DELETE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_SALES,
    PERMISSIONS.REPORTS_REPAIRS,
    PERMISSIONS.REPORTS_STOCK,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DEVELOPER_VIEW,
    PERMISSIONS.DEVELOPER_MANAGE,
  ],
  TECNICO: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPAIRS_VIEW,
    PERMISSIONS.REPAIRS_EDIT,
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_MOVEMENTS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
  ],
  VENDEDOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CLIENTS_VIEW,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_EDIT,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_EDIT,
    PERMISSIONS.CASH_VIEW,
    PERMISSIONS.CASH_OPEN,
    PERMISSIONS.CASH_CLOSE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_SALES,
  ],
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
